<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Profile Programistów Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'Email' => array(
			'type' => 'email',
			'label' => 'Od',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Od\' is required.',
				'format' => 'Field \'Od\' has an invalid email.'
			)
		),
		'custom_U988' => array(
			'type' => 'checkbox',
			'label' => 'Java',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Java\' is required.'
			)
		),
		'custom_U1004' => array(
			'type' => 'checkbox',
			'label' => 'C#',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'C#\' is required.'
			)
		),
		'custom_U1008' => array(
			'type' => 'checkbox',
			'label' => 'HTML/CSS',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'HTML/CSS\' is required.'
			)
		),
		'custom_U1000' => array(
			'type' => 'checkbox',
			'label' => 'JavaScript',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'JavaScript\' is required.'
			)
		),
		'custom_U1012' => array(
			'type' => 'checkbox',
			'label' => 'SQL',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'SQL\' is required.'
			)
		),
		'custom_U992' => array(
			'type' => 'checkbox',
			'label' => 'Android',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Android\' is required.'
			)
		),
		'custom_U1040' => array(
			'type' => 'string',
			'label' => 'Do',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Do\' is required.'
			)
		),
		'custom_U1020' => array(
			'type' => 'checkbox',
			'label' => 'Python',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Python\' is required.'
			)
		),
		'custom_U984' => array(
			'type' => 'checkbox',
			'label' => 'PHP',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PHP\' is required.'
			)
		),
		'custom_U1032' => array(
			'type' => 'checkbox',
			'label' => 'brak',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'brak\' is required.'
			)
		),
		'custom_U1048' => array(
			'type' => 'checkbox',
			'label' => 'ukończone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ukończone\' is required.'
			)
		),
		'custom_U1036' => array(
			'type' => 'checkbox',
			'label' => 'Junior',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Junior\' is required.'
			)
		),
		'custom_U1016' => array(
			'type' => 'checkbox',
			'label' => 'Regular',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Regular\' is required.'
			)
		),
		'custom_U1044' => array(
			'type' => 'checkbox',
			'label' => 'Senior',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Senior\' is required.'
			)
		)
	)
);

process_form($form);
?>
