<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Zaloguj Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'oferty-pracy.html',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U275' => array(
			'type' => 'string',
			'label' => 'Adres email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Adres email\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Hasło',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Hasło\' is required.',
				'format' => 'Field \'Hasło\' has an invalid email.'
			)
		)
	)
);

process_form($form);
?>
