<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Kontakt Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U623' => array(
			'type' => 'string',
			'label' => 'Nazwisko',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nazwisko\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Adres email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Adres email\' is required.',
				'format' => 'Field \'Adres email\' has an invalid email.'
			)
		),
		'custom_U629' => array(
			'type' => 'string',
			'label' => 'Wiadomość',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U645' => array(
			'type' => 'string',
			'label' => 'Imie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Imie\' is required.'
			)
		)
	)
);

process_form($form);
?>
