<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Zarejestruj Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U589' => array(
			'type' => 'string',
			'label' => 'Adres email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Adres email\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Hasło',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Hasło\' is required.',
				'format' => 'Field \'Hasło\' has an invalid email.'
			)
		),
		'custom_U601' => array(
			'type' => 'string',
			'label' => 'Potwierdź hasło',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Potwierdź hasło\' is required.'
			)
		),
		'custom_U605' => array(
			'type' => 'string',
			'label' => 'Firma',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Firma\' is required.'
			)
		),
		'custom_U609' => array(
			'type' => 'string',
			'label' => 'Telefon',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefon\' is required.'
			)
		)
	)
);

process_form($form);
?>
