<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Oferty Pracy Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'Email' => array(
			'type' => 'email',
			'label' => 'Min',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Min\' is required.',
				'format' => 'Field \'Min\' has an invalid email.'
			)
		),
		'custom_U758' => array(
			'type' => 'checkbox',
			'label' => 'dolnośląske',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'dolnośląske\' is required.'
			)
		),
		'custom_U794' => array(
			'type' => 'checkbox',
			'label' => 'kujawsko-pomorskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'kujawsko-pomorskie\' is required.'
			)
		),
		'custom_U798' => array(
			'type' => 'checkbox',
			'label' => 'lubelskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'lubelskie\' is required.'
			)
		),
		'custom_U802' => array(
			'type' => 'checkbox',
			'label' => 'lubuskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'lubuskie\' is required.'
			)
		),
		'custom_U806' => array(
			'type' => 'checkbox',
			'label' => 'łódzkie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'łódzkie\' is required.'
			)
		),
		'custom_U810' => array(
			'type' => 'checkbox',
			'label' => 'małopolskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'małopolskie\' is required.'
			)
		),
		'custom_U821' => array(
			'type' => 'string',
			'label' => 'Max',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Max\' is required.'
			)
		),
		'custom_U825' => array(
			'type' => 'checkbox',
			'label' => 'mazowieckie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'mazowieckie\' is required.'
			)
		),
		'custom_U829' => array(
			'type' => 'checkbox',
			'label' => 'opolskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'opolskie\' is required.'
			)
		),
		'custom_U833' => array(
			'type' => 'checkbox',
			'label' => 'podkarpackie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'podkarpackie\' is required.'
			)
		),
		'custom_U837' => array(
			'type' => 'checkbox',
			'label' => 'pomorskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'pomorskie\' is required.'
			)
		),
		'custom_U841' => array(
			'type' => 'checkbox',
			'label' => 'podlaskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'podlaskie\' is required.'
			)
		),
		'custom_U845' => array(
			'type' => 'checkbox',
			'label' => 'swietokrzyskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'swietokrzyskie\' is required.'
			)
		),
		'custom_U849' => array(
			'type' => 'checkbox',
			'label' => 'śląskie',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'śląskie\' is required.'
			)
		),
		'custom_U866' => array(
			'type' => 'checkbox',
			'label' => 'Junior',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Junior\' is required.'
			)
		),
		'custom_U870' => array(
			'type' => 'checkbox',
			'label' => 'Regular',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Regular\' is required.'
			)
		),
		'custom_U874' => array(
			'type' => 'checkbox',
			'label' => 'Senior',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Senior\' is required.'
			)
		)
	)
);

process_form($form);
?>
